spring:
  application:
    name: facility-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  config:
    import: "optional:configserver:http://localhost:8888"


# Eureka client

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8762/eureka/}
    register-with-eureka: true
    fetch-registry: true
